#ifndef BASEOPERATELIB_GLOBAL_H
#define BASEOPERATELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BASEOPERATELIB_LIB
# define BASEOPERATELIB_EXPORT Q_DECL_EXPORT
#else
# define BASEOPERATELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEOPERATELIB_GLOBAL_H
