#ifndef COORDTRANSFORM_GLOBAL_H
#define COORDTRANSFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COORDTRANSFORM_LIB
# define COORDTRANSFORM_EXPORT Q_DECL_EXPORT
#else
# define COORDTRANSFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // COORDTRANSFORM_GLOBAL_H
